<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>ImgToVideo.Ffmpeg</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ImgToVideo.Core\ImgToVideo.Core.csproj" />
  </ItemGroup>

</Project>
