<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>ImgToVideo.App</RootNamespace>
    <AssemblyName>ImgToVideo</AssemblyName>
    <ApplicationIcon>imgtovideo_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="imgtovideo_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ImgToVideo.Core\ImgToVideo.Core.csproj" />
    <ProjectReference Include="..\ImgToVideo.Ffmpeg\ImgToVideo.Ffmpeg.csproj" />
    <ProjectReference Include="..\ImgToVideo.Premiere\ImgToVideo.Premiere.csproj" />
  </ItemGroup>

</Project>
