<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ImgToVideo.Core\ImgToVideo.Core.csproj" />
    <ProjectReference Include="..\ImgToVideo.Ffmpeg\ImgToVideo.Ffmpeg.csproj" />
  </ItemGroup>
</Project>
