using System.Globalization;
using System.Net;
using System.Text;

namespace ImgToVideo.ImageGen;

public enum ReviewStatus
{
    Generated,
    Existing,
    Failed,
}

public sealed record ReviewItem(string FileName, string Prompt, ReviewStatus Status, string Detail);

/// <summary>Writes a self-contained HTML contact sheet next to the images for the review pass.</summary>
public static class ContactSheetWriter
{
    public static void Write(string path, string title, IReadOnlyList<ReviewItem> items)
    {
        var generated = items.Count(i => i.Status == ReviewStatus.Generated);
        var existing = items.Count(i => i.Status == ReviewStatus.Existing);
        var failed = items.Count(i => i.Status == ReviewStatus.Failed);

        var cards = new StringBuilder();
        foreach (var item in items)
        {
            var (badge, badgeClass) = item.Status switch
            {
                ReviewStatus.Generated => ("generated", "ok"),
                ReviewStatus.Existing => ("already on disk", "skip"),
                _ => ("FAILED", "fail"),
            };

            cards.Append("<div class=\"card\">");
            if (item.Status != ReviewStatus.Failed)
            {
                cards.Append(CultureInfo.InvariantCulture,
                    $"<img src=\"../images/{Html(item.FileName)}\" loading=\"lazy\" alt=\"{Html(item.FileName)}\"/>");
            }
            else
            {
                cards.Append("<div class=\"missing\">generation failed</div>");
            }

            cards.Append(CultureInfo.InvariantCulture,
                $"<div class=\"info\"><div class=\"file\"><span class=\"{badgeClass}\">[{badge}]</span> {Html(item.FileName)}</div>" +
                $"<div class=\"prompt\">{Html(item.Prompt)}</div>");
            if (item.Detail.Length > 0)
            {
                cards.Append(CultureInfo.InvariantCulture,
                    $"<div class=\"detail\">{Html(item.Detail)}</div>");
            }

            cards.Append("</div></div>");
        }

        var template = """
            <!doctype html>
            <html><head><meta charset="utf-8"/><title>Image review — @TITLE@</title>
            <style>
              body { font-family: 'Segoe UI', sans-serif; background: #14161a; color: #d8dade; margin: 0; padding: 16px 20px; }
              h1 { font-size: 18px; font-weight: 600; }
              .summary { color: #8b909a; font-size: 12.5px; margin-bottom: 14px; }
              .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(330px, 1fr)); gap: 12px; }
              .card { background: #1e2127; border: 1px solid #33363d; border-radius: 6px; overflow: hidden; }
              .card img { width: 100%; display: block; background: #000; }
              .missing { height: 120px; display: flex; align-items: center; justify-content: center; color: #f27979; font-size: 13px; background: #241c1e; }
              .info { padding: 8px 10px 10px; }
              .file { font-size: 12.5px; font-weight: 600; word-break: break-all; }
              .prompt { font-size: 11.5px; color: #9aa0aa; margin-top: 4px; line-height: 1.45; }
              .detail { font-size: 11.5px; color: #c9a0a0; margin-top: 4px; }
              .ok { color: #7ecb9c; }
              .skip { color: #8b909a; }
              .fail { color: #f27979; }
            </style></head><body>
            <h1>Image review — @TITLE@</h1>
            <div class="summary">@SUMMARY@</div>
            <div class="grid">@CARDS@</div>
            </body></html>
            """;

        var html = template
            .Replace("@TITLE@", Html(title))
            .Replace("@SUMMARY@", string.Create(CultureInfo.InvariantCulture,
                $"{generated} generated · {existing} already on disk · {failed} failed — failed files can be regenerated by running the tool again (existing files are skipped)."))
            .Replace("@CARDS@", cards.ToString());

        File.WriteAllText(path, html, Encoding.UTF8);
    }

    private static string Html(string text) => WebUtility.HtmlEncode(text);
}

